export type LegalKind = "privacy" | "terms";

export type LegalSection = {
  heading: string;
  body: string;
  bullets?: string[];
};

export const LEGAL_CONTACT_EMAIL = "support@playinweb.com";

export const LEGAL_UPDATED = "September 25, 2026";

export const LEGAL_DOCS: Record<LegalKind, { title: string; intro: string; sections: LegalSection[] }> = {
  privacy: {
    title: "Privacy Policy",
    intro:
      "PlayInWeb (“we”, “us”, “our”) operates https://www.playinweb.com and related subdomains. This Privacy Policy explains what personal information we collect, how we use and share it, how long we keep it, and what choices you have. It applies when you browse, play games, create an account, sign in with Google, publish games, donate, tip, cash out, or contact us. By using PlayInWeb you agree to this policy. If you do not agree, please do not use the service.",
    sections: [
      {
        heading: "Who we are and how to contact us",
        body: `PlayInWeb is the data controller for personal information described in this policy. We are responsible for deciding how your data is used to operate the catalogue, accounts, payments, and support. For privacy questions, account deletion requests, or data access requests, email ${LEGAL_CONTACT_EMAIL} or use Report an issue on the site. We will respond within a reasonable time.`,
      },
      {
        heading: "Information we collect",
        body: "We collect information you provide, information generated by your use of PlayInWeb, and information from service providers. The categories below describe what we may collect depending on how you use the site.",
        bullets: [
          "Identity and account: email address, password (stored as a hash, never in plain text), session tokens, account creation date, and one-time codes when you verify a PayPal email for payouts.",
          "Profile and public channel: handle, display name, biography, avatar image, banner image, public page URL, follower count, and any PayPal email you connect for creator payouts.",
          "Google Sign-In: if you choose Continue with Google, we receive from Google the information you authorize, typically your name, email address, Google account identifier, and profile picture URL. We use this to create or sign in to your PlayInWeb account. We do not receive your Google password. Google’s use of your data is governed by Google’s Privacy Policy at https://policies.google.com/privacy.",
          "Games and uploads: game title, slug, descriptions, tags, cover art, screenshots, trailer links, play URLs, store links, publish status, pricing settings, and HTML or other files you upload for hosted play.",
          "Social and activity: comments and replies, likes on games and comments, follows, library and collection saves, play history stored on our servers where applicable, play counts, view counts, and download activity for files you attach to listings.",
          "Payments: Polar checkout and payment identifiers, donation and tip amounts, platform commission rate, donor display name or email when you provide it, payout records, and payout status. We do not store full payment card numbers.",
          "Support and reports: subject line and message body from Report an issue, associated account email, and timestamps.",
          "Technical and usage: pages visited, referrer, device/browser type, approximate location derived from IP (as processed by our analytics provider), authentication cookies, and error logs needed to secure and operate the service.",
          "On your device (local storage): theme preference, sidebar state, notification read time, cached catalogue data, guest play timer, local play history, and similar settings that stay in your browser until you clear site data.",
        ],
      },
      {
        heading: "How we use your information",
        body: "We use personal information for the following purposes:",
        bullets: [
          "Provide the service: create accounts, authenticate you (including via Google), host and display games, serve your public channel, and keep you signed in.",
          "Operate social features: comments, likes, follows, library, collections, notifications, and popularity rankings.",
          "Process payments: run Polar checkouts for donations and tips, calculate platform commission, record earnings, and send PayPal payouts to confirmed addresses.",
          "Safety and integrity: investigate abuse, respond to reports, prevent fraud, enforce our Terms, and protect users and the platform.",
          "Improve PlayInWeb: understand which pages and features are used through aggregate analytics so we can fix bugs and improve performance.",
          "Communicate with you: send account-related messages such as email confirmation, password reset links, and PayPal verification codes.",
          "Comply with law: respond to lawful requests and maintain records required for tax, fraud prevention, or dispute resolution.",
        ],
      },
      {
        heading: "Legal bases (EEA/UK users)",
        body: "If you are in the European Economic Area or United Kingdom, we process personal data on these bases: (1) contract — to provide the account, hosting, and payment features you request; (2) legitimate interests — to secure the platform, prevent abuse, and improve the service in ways that do not override your rights; (3) consent — where required, for example optional marketing if we add it in future; (4) legal obligation — where we must retain payment or identity records.",
      },
      {
        heading: "What is public",
        body: "Anyone who opens PlayInWeb can see public profiles, published games, play and view totals, likes, comments, follower counts, and channel pages. Do not put secrets in bios, comments, or game listings. Unpublished games stay visible only to you (and site operators as needed to run the service).",
      },
      {
        heading: "How we use data",
        body: "We use this information to provide and improve the service:",
        bullets: [
          "Create and secure your account, and show your channel.",
          "Host, list, and serve games, covers, screenshots, and files.",
          "Count plays and views, and show popularity, history, and notifications.",
          "Run likes, comments, follows, library, collections, and downloads.",
          "Process donations and tips through Polar, apply the platform fee shown at checkout, and record payouts to a confirmed PayPal email.",
          "Handle reports, hide or remove content that breaks the terms, and operate admin tools.",
          "Measure traffic with Vercel Analytics so we know which pages are used.",
        ],
      },
      {
        heading: "How we share information",
        body: "We do not sell your personal information. We share data only as described below:",
        bullets: [
          "Public on PlayInWeb: profile pages, published games, comments, like counts, follower counts, and channel URLs are visible to anyone who visits the site.",
          "Service providers (processors): Supabase (authentication, database, file storage), Vercel (hosting and analytics), Polar (payment processing), PayPal (payout delivery), and Google (only when you choose Google Sign-In, under Google’s terms).",
          "Legal and safety: we may disclose information if required by law, court order, or government request, or when we believe disclosure is necessary to protect rights, safety, or property.",
          "Business changes: if PlayInWeb is involved in a merger, acquisition, or asset sale, user information may transfer as part of that transaction with notice where required by law.",
        ],
      },
      {
        heading: "Service providers",
        body: "Each vendor processes data under its own privacy policy and only for the services it provides to us:",
        bullets: [
          "Supabase — https://supabase.com/privacy (auth, database, storage).",
          "Vercel — https://vercel.com/legal/privacy-policy (hosting, Vercel Analytics).",
          "Polar — https://polar.sh/legal/privacy (checkout and payments).",
          "PayPal — https://www.paypal.com/us/legalhub/privacy-full (payout accounts you connect).",
          "Google — https://policies.google.com/privacy (Sign in with Google only, when you use it).",
        ],
      },
      {
        heading: "Cookies and your device",
        body: "Sign-in uses cookies so you stay logged in. Your browser may also store:",
        bullets: [
          "Theme (light or dark).",
          "Whether the sidebar is minimized.",
          "When you last opened notifications.",
          "Local play history and related library data.",
          "A short cache of the game catalogue.",
          "Local follow or Game showcase bid drafts, where those features use the browser only.",
          "Session flags so we do not double-count a play or view in the same tab session.",
        ],
      },
      {
        heading: "Retention",
        body: "Account, profile, games, comments, follows, likes, donations, tips, payouts, and reports stay until you delete them or we remove them under the terms (for example abuse). Cached catalogue data expires after a few minutes. Local browser data lasts until you clear site data. Analytics is kept in aggregate form by Vercel under their retention rules.",
      },
      {
        heading: "Your choices and rights",
        body: "Depending on where you live, you may have rights to access, correct, delete, or export your personal information, and to object to or restrict certain processing. You can take many steps yourself in the product:",
        bullets: [
          "Edit or delete profile information and unpublish or remove games you own.",
          "Unlike, unfollow, and delete comments you posted where the product allows.",
          "Sign out, clear browser cookies, or clear site data to remove local storage items.",
          "Disconnect PayPal payout email in Donations settings.",
          "Revoke Google’s access to PlayInWeb in your Google Account security settings at https://myaccount.google.com/permissions.",
          "Request account deletion by emailing support@playinweb.com or using Report an issue. We will delete or anonymize data we control, except records we must keep for legal, tax, fraud, or payment dispute reasons.",
        ],
      },
      {
        heading: "California privacy rights",
        body: "If you are a California resident, you may have rights under the CCPA/CPRA including the right to know what personal information we collect, request deletion, and opt out of the sale of personal information. We do not sell personal information. To exercise rights, contact support@playinweb.com. We will not discriminate against you for exercising privacy rights.",
      },
      {
        heading: "Security",
        body: "We use HTTPS encryption in transit, access controls on our database and storage, and reputable vendors for authentication and payments. No online service can guarantee absolute security. If we learn of a breach affecting your personal information, we will notify you and regulators as required by law.",
      },
      {
        heading: "International transfers",
        body: "PlayInWeb is operated from Indonesia. Our service providers (Supabase, Vercel, Polar, PayPal, Google) may process data in the United States and other countries. Where required, we rely on appropriate safeguards such as standard contractual clauses offered by our vendors. By using PlayInWeb you understand your information may be transferred internationally.",
      },
      {
        heading: "Children",
        body: "PlayInWeb is not directed at children under 13 (or the higher age required in your country). We do not knowingly collect personal information from children. If you believe a child has provided us data, contact support@playinweb.com and we will delete the account and associated information.",
      },
      {
        heading: "Changes to this policy",
        body: "We may update this Privacy Policy when our practices change. We will post the new version on this page and update the “Last updated” date. Material changes may also be noted on the site. Continued use after an update means you accept the revised policy.",
      },
      {
        heading: "Contact",
        body: `Questions about this Privacy Policy or your personal data: ${LEGAL_CONTACT_EMAIL}. PlayInWeb — https://www.playinweb.com`,
      },
    ],
  },
  terms: {
    title: "Terms",
    intro:
      "These terms are a contract between you and PlayInWeb. By browsing, playing, signing up, publishing, donating, tipping, or cashing out, you agree to them. If you do not agree, do not use the site.",
    sections: [
      {
        heading: "The service",
        body: "PlayInWeb is a catalogue of indie web games. We may list games, host HTML builds you upload, show trailers and store links, and provide accounts, comments, likes, follows, library, collections, downloads, donations, tips, and payouts. Some items in the navigation may be marked Soon or hidden. We can add, change, or remove features without notice. We do not guarantee uptime, that a game will keep working, or that a checkout will succeed.",
      },
      {
        heading: "Eligibility",
        body: "You must be old enough to form a contract in your country (and at least 13). If you use Polar or PayPal you must also meet their age and identity rules. You are responsible for keeping your email and password secret and for everything done under your handle.",
      },
      {
        heading: "Accounts",
        body: "One person should use one account. Handles must follow the format we allow and must not impersonate others or use reserved names. We may refuse, suspend, or delete an account that is abusive, fraudulent, inactive, or in breach of these terms. If your account is removed, public comments and listings may be hidden; payment records may be retained.",
      },
      {
        heading: "License to use PlayInWeb",
        body: "We grant you a limited, revocable, non-exclusive license to use the site for personal play and, if you have an account, to publish games you have the right to share. You may not scrape the site in a way that harms the service, copy another creator's files without permission, bypass pay or commission flows, or probe the site for security holes except through Report an issue.",
      },
      {
        heading: "Publishing games",
        body: "You keep ownership of games, art, audio, and code you upload. You grant PlayInWeb a worldwide license to host, cache, display, embed, and stream that material so people can browse and play on PlayInWeb, including covers, screenshots, trailers, and HTML files. You promise that you have the rights needed, that the build is not malware, and that it does not include sexual content involving minors, illegal content, or material that exploits anyone. File size and format limits we show in the publisher apply. Keep your own backups. We are not a long-term archive.",
      },
      {
        heading: "Comments and social features",
        body: "Comments, likes, follows, and collection names are your content. Do not harass, spam, or post illegal material. We may remove or hide social content and may limit who can comment. Public social data can be seen by anyone on the site.",
      },
      {
        heading: "Donations and tips",
        body: "Donations to a game and tips to PlayInWeb are processed by Polar. Amounts, currency, taxes, and refunds follow Polar's terms and the checkout screen. PlayInWeb keeps a platform commission on donations at the rate shown when you pay (set in site settings, typically around 10%). That cut stays with the site. The remainder is what the creator can cash out, subject to payout rules. Tips to the site are not donations to a game listing. We do not store card numbers.",
      },
      {
        heading: "Payouts",
        body: "Creators may connect a PayPal email after proving they control the PlayInWeb account (including email confirmation codes we send). Payouts are sent only to that confirmed email, subject to a minimum balance we display (currently the amount shown on the Donations page). Polar must have paid the checkout before we treat funds as available. We may delay, reverse, or refuse a payout if we suspect fraud, chargebacks, or terms violations. PayPal's terms apply to the receiving account. You are responsible for any tax on amounts you receive.",
      },
      {
        heading: "Downloads and third-party links",
        body: "Files attached to a listing are provided by the creator. Play at your own risk. Store links, trailers, and off-site play URLs are third-party services. Their terms and privacy rules apply. PlayInWeb is not responsible for those sites or for damage caused by a downloaded file.",
      },
      {
        heading: "Prohibited use",
        body: "You may not:",
        bullets: [
          "Upload malware, exploits, or games designed to steal accounts or data.",
          "Infringe copyrights, trademarks, or other rights.",
          "Post sexual content involving anyone 17 or under, or any exploitative sexual content.",
          "Harass users, scrape personal data, or spam comments and follows.",
          "Interfere with Polar, PayPal, or our billing and commission.",
          "Impersonate PlayInWeb, another creator, or a payment provider.",
        ],
      },
      {
        heading: "Moderation",
        body: "We may hide, unpublish, or delete listings, files, comments, or accounts that break these terms or the law, or that harm the service. Report an issue is the way to flag problems. We may not discuss every action we take. Repeat or severe abuse can lead to a permanent ban.",
      },
      {
        heading: "Intellectual property of PlayInWeb",
        body: "The PlayInWeb name, logo, and site design are ours. You may not use them to suggest we endorse a game unless we say so in writing. Games remain their creators' property as described above.",
      },
      {
        heading: "Disclaimer",
        body: "THE SITE AND ALL GAMES ARE PROVIDED AS-IS, WITHOUT WARRANTIES OF ANY KIND, INCLUDING MERCHANTABILITY, FITNESS FOR A PURPOSE, OR NON-INFRINGEMENT. Games can crash, contain bugs, or be taken down. Play sessions, counts, and rankings may be wrong or reset.",
      },
      {
        heading: "Limitation of liability",
        body: "To the fullest extent allowed by law, PlayInWeb and its operators are not liable for lost profits, lost data, lost game files, or indirect or consequential damages, or for amounts greater than the fees you paid to PlayInWeb in the three months before a claim (or, if you paid nothing, a small nominal amount). Some places do not allow these limits; in those places our liability is limited as much as the law allows.",
      },
      {
        heading: "Indemnity",
        body: "If your content or conduct causes a claim against PlayInWeb (including a Polar or PayPal dispute we did not cause), you will cover reasonable costs we incur, including legal fees, except where we are solely at fault.",
      },
      {
        heading: "Changes and contact",
        body: "We may update these terms. The date at the top is the latest version. If a change is material we may note it on the site. Continued use after an update is acceptance. Questions go through Report an issue. These terms are the whole agreement for use of PlayInWeb and sit alongside Polar and PayPal terms for payments.",
      },
    ],
  },
};
